// server/scripts/tree.js
const fs = require('fs');
const path = require('path');

const IGNORE = new Set(['node_modules', '.git', 'dist', '.vscode', 'coverage', 'package-lock.json']);
const OUTPUT_FILE = path.join(__dirname, '../../STRUCTURE.md');
const ROOT_DIR = path.join(__dirname, '..');

function getTree(dir, prefix = '') {
  const name = path.basename(dir);
  if (IGNORE.has(name)) return '';

  let output = '';
  const isRoot = dir === ROOT_DIR;
  
  // Format nama folder/file
  if (!isRoot) {
    output += `${prefix}${name}\n`;
  }

  // Cek apakah ini directory
  let stats;
  try {
    stats = fs.statSync(dir);
  } catch (e) { return ''; }

  if (stats.isDirectory()) {
    const children = fs.readdirSync(dir).filter(child => !IGNORE.has(child));
    // Sort biar folder di atas, file di bawah, urut abjad
    children.sort((a, b) => {
        const aStat = fs.statSync(path.join(dir, a));
        const bStat = fs.statSync(path.join(dir, b));
        if (aStat.isDirectory() && !bStat.isDirectory()) return -1;
        if (!aStat.isDirectory() && bStat.isDirectory()) return 1;
        return a.localeCompare(b);
    });

    children.forEach((child, index) => {
      const isLast = index === children.length - 1;
      const newPrefix = isRoot ? '' : prefix.replace('├── ', '│   ').replace('└── ', '    ');
      const connector = isLast ? '└── ' : '├── ';
      output += getTree(path.join(dir, child), isRoot ? '' : `${newPrefix}${connector}`);
    });
  }
  return output;
}

const header = `# TRUPEST Project Structure
> Last Updated: ${new Date().toLocaleString()}
> Auto-generated by scripts/tree.js

\`\`\`text
.
${getTree(ROOT_DIR)}
\`\`\`
`;

fs.writeFileSync(OUTPUT_FILE, header);
console.log(`✅ Structure snapshot saved to ${OUTPUT_FILE}`);